spring:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/proyecto
    username: root
    password: Mario12345

